site_name: AP Computer Science
site_url: https://dkessner.github.io/APCS

theme:
  name: material
  palette: 
    primary: deep orange
  logo: images/phyllotaxis_orange.png

extra_css:
  - style.css


nav:
  - Home: index.md
  - Class:
    - class/intro.md
